version: '3.8'

services:
  telegram-bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    restart: always
    networks:
      - botnet

  order-generator-service:
    hostname: order-generation-service
    build:
      context: ./order_generation_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - botnet

  db:
    hostname: customers-db
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - botnet

  warehouse_db:
    hostname: warehouse_db
    image: postgres:latest
    container_name: warehouse_db
    environment:
      POSTGRES_USER: ${WAREHOUSE_DB_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_DB_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB_NAME}
    networks:
      - botnet
    ports:
      - "5433:5432"
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data
      - ./init_warehouse.sql:/docker-entrypoint-initdb.d/init_warehouse.sql

networks:
  botnet:
    driver: bridge

volumes:
  db_data:
  warehouse_db_data: